/*
 * Ported from OptiLithium (https://github.com/Chocohead/OptiLithium), MPL-2.0.
 * Adapted for Minecraft 1.20.6 and 1.21.11 / Fabric Loader 0.19.x.
 *
 * Changes from upstream:
 *   - no Fabric-ASM / com.chocohead.mm dependency (the jar is handed to Fabric Loader instead);
 *   - tiny-remapper is taken from the copy Fabric Loader ships (relocated to
 *     net.fabricmc.loader.impl.lib.tinyremapper), so nothing extra has to be bundled;
 *   - the mappings come from the intermediary mappings bundled into this jar by the build;
 *   - development environments (runtime namespace "named") are refused with a clear message instead
 *     of being remapped through the extra contextual mapping layer upstream needed for them.
 */
package kynarain.cn.optilithium.mod;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.lang.reflect.Method;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import java.util.stream.Stream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipException;
import java.util.zip.ZipFile;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.tree.ClassNode;

import net.fabricmc.loader.api.FabricLoader;
import net.fabricmc.loader.impl.launch.FabricLauncherBase;

import net.fabricmc.loader.impl.lib.mappingio.MappingReader;
import net.fabricmc.loader.impl.lib.mappingio.tree.MemoryMappingTree;
import net.fabricmc.loader.impl.lib.tinyremapper.IMappingProvider;
import net.fabricmc.loader.impl.lib.tinyremapper.InputTag;
import net.fabricmc.loader.impl.lib.tinyremapper.NonClassCopyMode;
import net.fabricmc.loader.impl.lib.tinyremapper.OutputConsumerPath;
import net.fabricmc.loader.impl.lib.tinyremapper.TinyRemapper;
import net.fabricmc.loader.impl.lib.tinyremapper.TinyUtils;
import net.fabricmc.loader.impl.lib.tinyremapper.api.TrLogger;

import kynarain.cn.optilithium.mod.OptifineVersion.JarType;
import kynarain.cn.optilithium.patcher.ClassCache;
import kynarain.cn.optilithium.patcher.LambdaRebuilder;
import kynarain.cn.optilithium.util.ASMUtils;
import kynarain.cn.optilithium.util.ZipUtils;
import kynarain.cn.optilithium.util.ZipUtils.ZipTransformer;
import kynarain.cn.optilithium.util.ZipUtils.ZipVisitor;

/**
 * Turns the OptiFine jar from the mods folder into something Fabric can run:
 * runs the OptiFine patcher over the vanilla (obfuscated) Minecraft jar, fixes up lambdas, remaps
 * everything from the official namespace to intermediary, and splits the result into
 * <ul>
 *   <li>a jar with OptiFine's own classes and resources, which goes on the game classpath, and</li>
 *   <li>a cache of patched Minecraft classes, which replace the game's version at class load time.</li>
 * </ul>
 * Both are cached in {@code .optilithium/<version>/} inside the game directory.
 */
public class OptifineSetup {
	public static OptifineRuntime getRuntime() throws IOException {
		// ".optilithium", not ".optifine": the cache is keyed only by the OptiFine version, so sharing the
		// directory with OptiFabric would let the two mods hand each other class caches produced by
		// different pipelines. That is exactly the trap that made the first rig runs unreadable - a run
		// that was meant to be clean silently reused the other mod's cached bytecode.
		File workingDir = new File(FabricLoader.getInstance().getGameDirectory(), ".optilithium");

		if (!workingDir.exists() && !workingDir.mkdirs()) throw new IOException("Failed to create " + workingDir);

		File optifineModJar = OptifineVersion.findOptifineJar();
		byte[] modHash = md5(optifineModJar);

		File versionDir = new File(workingDir, OptifineVersion.version);
		if (!versionDir.exists() && !versionDir.mkdirs()) throw new IOException("Failed to create " + versionDir);

		File remappedJar = new File(versionDir, "Optifine-mapped.jar");
		File optifinePatches = new File(versionDir, "Optifine.classes.gz");
		File cacheStamp = new File(versionDir, "cache-format.txt");

		//Artifacts produced by an older pipeline must not be reused: the cache format is bumped whenever
		//the generated bytes would change (e.g. stack map frames no longer being dropped).
		boolean cacheUsable = remappedJar.exists() && optifinePatches.exists() && cacheStamp.exists()
				&& String.valueOf(CACHE_FORMAT).equals(Files.readString(cacheStamp.toPath(), StandardCharsets.UTF_8).trim());

		if (cacheUsable) {
			ClassCache classCache = ClassCache.read(optifinePatches);

			//Validate that the classCache found is for the same input jar
			if (Arrays.equals(classCache.getHash(), modHash)) {
				System.out.println("[OptiLithium] Found existing patched OptiFine jar, using that");

				if (classCache.isConverted()) {
					classCache.save(optifinePatches);
				}

				return new OptifineRuntime(remappedJar.toPath(), classCache);
			} else {
				System.out.println("[OptiLithium] Class cache is from a different OptiFine jar, deleting and re-generating");
			}
		} else {
			if (remappedJar.exists() || optifinePatches.exists()) {
				System.out.println("[OptiLithium] Patched OptiFine cache is from an older OptiLithium, regenerating it");
			} else {
				System.out.println("[OptiLithium] Setting up OptiFine for the first time, this may take a few seconds.");
			}
		}

		//Which namespace the game actually runs in, which is what decides whether OptiFine's classes have to be
		//renamed at all. Fabric Loader says "intermediary" for the obfuscated releases this mod started on, but
		//"official" for a release that ships unobfuscated (Minecraft 26.1 and newer): those publish only the empty
		//placeholder intermediary 0.0.0, so MappingConfiguration.hasAnyMappings() is false and
		//computeRuntimeNamespace() falls back to "official" instead of entering its intermediary branch.
		String namespace = FabricLoader.getInstance().getMappingResolver().getCurrentRuntimeNamespace();

		if (!"intermediary".equals(namespace) && !"official".equals(namespace)) {
			throw new IllegalStateException("OptiLithium can currently only load OptiFine in a production runtime"
					+ " (namespace \"intermediary\" or \"official\"), but this instance runs in the \"" + namespace + "\" namespace.\n"
					+ "Run the built OptiLithium jar in a normal launcher with Fabric Loader and OptiFine in the"
					+ " mods folder instead of launching it from a development environment.");
		}

		Path minecraftJar = getMinecraftJar();
		File workDir = Files.createTempDirectory("optilithium").toFile();

		if (OptifineVersion.jarType == JarType.OPTIFINE_INSTALLER) {
			File optifineMod = new File(workDir, "Optifine-mod.jar");

			out: if (!optifineMod.exists() || !ZipUtils.isValid(optifineMod)) {
				for (int attempt = 1; attempt <= 3; attempt++) {
					runInstaller(optifineModJar, optifineMod, minecraftJar.toFile());

					if (!ZipUtils.isValid(optifineMod)) {
						optifineMod.delete();
						continue;
					}

					break out; //Produced a valid extracted jar
				}

				OptifineVersion.jarType = JarType.CORRUPT_ZIP;
				OptilithiumError.setError("OptiFine installer keeps producing corrupt jars!\nRan: %s 3 times\nMinecraft jar: %s", optifineModJar, minecraftJar);
				throw new ZipException("Ran OptiFine installer (" + optifineModJar + ") three times without a valid jar produced");
			}

			optifineModJar = optifineMod;
		}

		//A jar without srgs
		File jarOfTheFree = new File(workDir, "Optifine-jarofthefree.jar");
		LambdaRebuilder rebuilder = new LambdaRebuilder(minecraftJar.toFile());

		System.out.println("[OptiLithium] De-Volderfiying jar");

		//Find all the SRG named classes and remove them
		ZipUtils.transform(optifineModJar, new ZipTransformer() {
			@Override
			public String mapName(ZipEntry entry) {
				String out = entry.getName();
				return out.startsWith("notch/") ? out.substring(6) : out;
			}

			@Override
			public InputStream apply(ZipFile zip, ZipEntry entry) throws IOException {
				String name = entry.getName();

				if (!name.startsWith("srg/")) {
					if (name.endsWith(".class") && !name.startsWith("net/") && !name.startsWith("notch/net/") && !name.startsWith("optifine/") && !name.startsWith("javax/")) {
						//The patched Minecraft classes: their lambdas point at the original methods, which moved.
						//Frames have to be read expanded - they are what keeps these classes verifiable once the
						//game loads them. Upstream read them with SKIP_FRAMES, which was harmless only because
						//Mixin happened to recompute the frames when it rewrote the class.
						ClassNode node = readClassWithFrames(zip, entry);
						rebuilder.findLambdas(node);

						ClassWriter writer = new ClassWriter(0);
						node.accept(writer);
						return new ByteArrayInputStream(writer.toByteArray());
					} else {
						return zip.getInputStream(entry);
					}
				} else {
					return null;
				}
			}
		}, jarOfTheFree);
		rebuilder.close();

		//In the "official" namespace the game's own names already are the runtime names, so OptiFine's patches are
		//named correctly as they stand and the whole official -> intermediary remap is the identity. It cannot just be
		//left in and allowed to be a no-op either: a jar is built for exactly one of the two worlds, and the build for
		//an unobfuscated release deliberately bundles no mappings at all (there would be nothing for the remapper to
		//read), so the step is skipped outright.
		File completeJar;

		if (OptifineMappings.OFFICIAL.equals(namespace)) {
			System.out.println("[OptiLithium] Minecraft " + OptifineVersion.minecraftVersion + " ships unobfuscated"
					+ " (runtime namespace \"" + namespace + "\"), so OptiFine needs no remapping");
			completeJar = jarOfTheFree;
		} else {
			System.out.println("[OptiLithium] Remapping OptiFine from official to " + namespace);
			completeJar = new File(workDir, "Optifine-remapped.jar");
			remapOptifine(jarOfTheFree, getLibs(), completeJar, createMappings(OptifineMappings.OFFICIAL, namespace));
		}

		File completedJar = completeJar;

		Consumer<ZipVisitor> jarFinaliser;
		if (remappedJar.exists() && !remappedJar.delete()) {
			System.err.println("[OptiLithium] Failed to clear " + remappedJar + ", is another instance of the game running?");
			remappedJar = completedJar;
			jarFinaliser = visitor -> ZipUtils.filterInPlace(completedJar, visitor);
		} else {
			final File finalRemappedJar = remappedJar; //It's final in this code path... but javac knows it's not final everywhere
			jarFinaliser = visitor -> ZipUtils.filter(completedJar, visitor, finalRemappedJar);
		}

		if (optifinePatches.exists() && !optifinePatches.delete()) {
			System.err.println("[OptiLithium] Failed to clear " + optifinePatches + ", is another instance of the game running?");
			optifinePatches = new File(workDir, "Optifine.classes.gz");
		}

		//We are done, lets get rid of the stuff we no longer need
		workDir.deleteOnExit();
		File[] leftOvers = workDir.listFiles();
		if (leftOvers != null) for (File file : leftOvers) file.deleteOnExit();

		boolean extract = Boolean.getBoolean("optilithium.extract");
		if (extract) {
			System.out.println("[OptiLithium] Extracting OptiFine classes");
			File optifineClasses = new File(versionDir, "optifine-classes");
			if (optifineClasses.exists()) {
				deleteRecursively(optifineClasses);
			}
			ZipUtils.extract(completedJar, optifineClasses);
		}

		ClassCache generated = generateClassCache(jarFinaliser, optifinePatches, modHash, extract);

		//OptiFine's own jar is not always right for the release it runs on (a post effect its build writes in a
		//shape that release cannot parse, a preview build that cancels the shaderpack load outright, and an FXAA
		//vertex shader written for the pipeline those releases no longer have); those entries are repaired in the
		//jar that is about to go on the class path.
		OptifineJarFixer.fix(remappedJar, getMinecraftJar());

		//OptiFine's own post-chain files are left exactly as they ship, on both lines. This used to be a repair
		//instead: builds since 1.21.8 no longer carry the pre-1.21.6 shaders/post/fxaa_of_*.json, so the pipeline
		//wrote that file and deleted OptiFine's post_effect/fxaa_of_*.json, on the theory that the two chain
		//runners would otherwise fight. Measured on 1.21.11 that is backwards - the chain id is resolved from
		//post_effect/ by the game's own loader (OptiFine patches ShaderManager to register it there), so deleting
		//it produces, on every resource reload,
		//
		//  [OptiLithium] Resource not found: minecraft:post_effect/fxaa_of_2x.json
		//
		// and then, as soon as anti-aliasing is switched on or a shaderpack is picked (both reload the shaders
		// and ask for the chain):
		//
		//  Failed to load post chain: minecraft:fxaa_of_2x
		//    class_10151$class_10152: Could not find post chain with id: minecraft:fxaa_of_2x
		//
		// The same pair of lines was then reproduced from the shipped jars on 1.21.3, 1.21.4, 1.21.7, 1.21.8,
		// 1.21.9 and 1.21.10 - the patched registration method is instruction-for-instruction identical from
		//1.21.8 to 1.21.11 and the request itself goes back to 1.21.3, so the repair was wrong for the whole
		//line. What the releases actually need instead is the shader repair in OptifineJarFixer. See
		//docs/DEVELOPMENT.md, "抗锯齿:链在哪一侧".
		System.out.println("[OptiLithium] Leaving OptiFine's post_effect/ files alone on "
				+ OptifineVersion.minecraftVersion + ": this release resolves the anti-aliasing chain there");

		Files.writeString(cacheStamp.toPath(), String.valueOf(CACHE_FORMAT), StandardCharsets.UTF_8);

		return new OptifineRuntime(remappedJar.toPath(), generated);
	}

	/**
	 * Bumped whenever the cached artifacts would come out different, so stale caches regenerate themselves.
	 * 3: the remap class path now contains the game, so members inherited from a supertype keep their name.
	 * 4: the game is also an input of the remap, so references to inherited members keep their mapped name too.
	 * 5: references to a renamed field are matched through the subclass that names it as their owner.
	 * 6: OptiFine's BlockEntity is applied instead of skipped, so its callers find what they call.
	 * 7: the vanilla bodies Fabric API injects into are restored again (three more of them).
	 * 8: ModelBakery's two wrap targets are restored, and LiquidBlockRenderer gets its call site back.
	 * 9-13: the fixers the 1.21.x series added or changed (details in the git history of this file).
	 * 14: classes no fixer modifies keep OptiFine's own stack map frames. They used to be recomputed for
	 *     every patched class (the global override fixer always reports a change), and the merge degraded
	 *     a local to java/lang/Object - which the game rejects with VerifyError.
	 * 15: two injections lost their points: the String constructor of ShaderProgram creates its Identifier the
	 *     way the game does again (Fabric API wraps that call), and the method references in the InGameHud
	 *     constructor point at methods the game declares again instead of OptiFine's lambdas.
	 * 16: OptiFine's own jar is repaired after remapping - its FXAA post effect is rewritten into the shape the
	 *     release parses, and the shaderpack load a 1.21.6 / 1.21.7 build cancels outright is enabled again.
	 * 17: that repair reads the method's instructions without the labels between them (16 could not see the
	 *     shaderpack load at all, so 16's artifacts are the unpatched ones).
	 * 18: OptiFine's factory calls are aligned with the game's, so the mixins that wrap them find them.
	 * 19: the custom shader textures of a 1.21.6 / 1.21.7 build are created through the game's GPU API instead
	 *     of the pre-1.21.6 GL API that no longer has an id to hand out.
	 * 25: the anti-aliasing chain repair is skipped on the releases that resolve the chain through the game's
	 *     post-chain loader (1.21.11), so their OptiFine jar keeps its own post_effect/ file instead of having it
	 *     replaced by the old-style one.
	 * 26: that repair is gone for the whole obfuscated line (the chain is resolved from post_effect/ on every
	 *     release since 1.21.3, so deleting OptiFine's copy was the bug), and the FXAA vertex shader of the
	 *     releases whose post pipeline is attribute-less (1.21.9 / 1.21.10) is rewritten to match it.
	 * Every bump is required, not cosmetic: artifacts produced by an older pipeline must not be reused.
	 * 27 (OptiLithium): RestoreSuperConstructorFix is registered for BlockEntity, so the patched classes come
	 *     out different from what OptiFabric and OptiLithium <= 26 produced. The bump is not optional - a
	 *     cache written by an earlier run is reused verbatim and the new fixer then never runs at all.
	 */
	private static final int CACHE_FORMAT = 27;

	/** Reads a class with its stack map frames expanded, so they survive the round trip (see the de-volderfy step). */
	private static ClassNode readClassWithFrames(ZipFile zip, ZipEntry entry) throws IOException {
		try (InputStream in = zip.getInputStream(entry)) {
			ClassNode node = new ClassNode();
			new ClassReader(in).accept(node, ClassReader.EXPAND_FRAMES);

			return node;
		}
	}

	private static void runInstaller(File installer, File output, File minecraftJar) throws IOException {
		System.out.println("[OptiLithium] Running OptiFine patcher");

		try (URLClassLoader classLoader = new URLClassLoader(new URL[] {installer.toURI().toURL()}, OptifineSetup.class.getClassLoader())) {
			Class<?> clazz = classLoader.loadClass("optifine.Patcher");
			Method method = clazz.getDeclaredMethod("process", File.class, File.class, File.class);
			method.invoke(null, minecraftJar, installer, output);
		} catch (ReflectiveOperationException e) {
			throw new RuntimeException("Error running OptiFine patcher at " + installer + " on " + minecraftJar, e);
		}
	}

	/**
	 * Remaps OptiFine's patched classes from the official namespace into the runtime one.
	 *
	 * <p>The class path given to the remapper is not optional detail: a member mapping is recorded for the class
	 * that <em>declares</em> the member, so a class that overrides it - very often an anonymous class implementing
	 * an interface, as {@code ModelManager$1} implements {@code SpriteGetter} - can only be named correctly while
	 * the supertype is visible. Without the game on the class path tiny-remapper cannot see the hierarchy and
	 * leaves those members under OptiFine's own name, which breaks the interface contract (AbstractMethodError),
	 * makes mods unable to shadow them and, in the 1.21.11 port, cost 281 broken contracts.</p>
	 */
	private static void remapOptifine(File input, Path[] libraries, File output, IMappingProvider mappings) throws IOException {
		Files.deleteIfExists(output.toPath());

		TrLogger logger = (level, message) -> System.out.println("[OptiLithium/remap] " + level + ": " + message);

		TinyRemapper remapper = TinyRemapper.newRemapper(logger)
				.withMappings(mappings)
				.renameInvalidLocals(false)
				.rebuildSourceFilenames(true)
				.build();

		InputTag tag = remapper.createInputTag();

		try (OutputConsumerPath outputConsumer = new OutputConsumerPath.Builder(output.toPath()).assumeArchive(true).build()) {
			outputConsumer.addNonClassFiles(input.toPath(), NonClassCopyMode.UNCHANGED, remapper);
			remapper.readInputsAsync(tag, input.toPath());
			remapper.readClassPathAsync(libraries);

			// The launcher class path normally contains the game already; adding it explicitly keeps the hierarchy
			// complete when it does not (and costs nothing when it does).
			Path minecraftJar = getMinecraftJar();
			if (Files.isRegularFile(minecraftJar) && Arrays.stream(libraries).noneMatch(minecraftJar::equals)) {
				remapper.readClassPathAsync(minecraftJar);
			}

			// The game also has to be an *input*, not only class path: a reference to an inherited member is
			// written with the subclass as its owner (BlockModelRenderer$AmbientOcclusionCalculator reads the
			// field its superclass declares), and resolving those is what the input pass does - with the class
			// path alone the declaration was renamed while its 19 references kept the official name, which is a
			// NoSuchFieldError waiting for the first ambient occlusion pass. Nothing of this tag is written;
			// apply() only consumes the tag of the classes we came for.
			InputTag gameTag = remapper.createInputTag();

			if (Files.isRegularFile(minecraftJar)) {
				remapper.readInputsAsync(gameTag, minecraftJar);
			}

			remapper.apply(outputConsumer, tag);
		} catch (Exception e) {
			throw new RuntimeException("Failed to remap jar", e);
		} finally {
			remapper.finish();
		}
	}

	/** Official (obfuscated) to the runtime namespace, using the mappings bundled into this jar by the build. */
	private static IMappingProvider createMappings(String from, String to) {
		return OptifineMappings.provider(from, to);
	}

	/** The launch classpath, which is in the official namespace and so is exactly what the remapper needs. */
	private static Path[] getLibs() {
		return FabricLauncherBase.getLauncher().getClassPath().stream().filter(Files::exists).toArray(Path[]::new);
	}

	/** The official (obfuscated) Minecraft client jar, which is what OptiFine's patcher expects. */
	private static Path getMinecraftJar() {
		String givenJar = System.getProperty("optilithium.mc-jar");
		if (givenJar != null) {
			File givenJarFile = new File(givenJar);

			if (givenJarFile.exists()) {
				return givenJarFile.toPath();
			} else {
				System.err.println("[OptiLithium] Supplied Minecraft jar at " + givenJar + " doesn't exist, falling back");
			}
		}

		Object single = FabricLoader.getInstance().getObjectShare().get("fabric-loader:inputGameJar");
		if (single instanceof Path path && Files.exists(path)) return path;

		Object all = FabricLoader.getInstance().getObjectShare().get("fabric-loader:inputGameJars");
		if (all instanceof List<?> list && !list.isEmpty() && list.get(0) instanceof Path path && Files.exists(path)) return path;

		throw new IllegalStateException("Unable to find the Minecraft jar OptiFine has to be patched into."
				+ " Please supply it explicitly with -Doptilithium.mc-jar=<path to the vanilla "
				+ OptifineVersion.minecraftVersion + " client jar>");
	}

	private static ClassCache generateClassCache(Consumer<ZipVisitor> from, File to, byte[] hash, boolean extractClasses) throws IOException {
		File classesDir = new File(to.getParent(), "classes");
		if (extractClasses) {
			if (classesDir.exists()) {
				deleteRecursively(classesDir);
			} else if (!classesDir.mkdirs()) {
				throw new IOException("Failed to create " + classesDir);
			}
		}
		ClassCache classCache = new ClassCache(hash);

		from.accept((jarFile, entry) -> {
			String name = entry.getName();

			if ((name.startsWith("net/minecraft/") || name.startsWith("com/mojang/")) && name.endsWith(".class")) {
				byte[] bytes;
				try (InputStream in = jarFile.getInputStream(entry)) {
					bytes = in.readAllBytes();
				}

				classCache.addClass(name.substring(0, name.length() - 6), bytes);
				if (extractClasses) {
					File extract = new File(classesDir, name);
					File parent = extract.getParentFile();
					if (parent != null) parent.mkdirs();
					Files.write(extract.toPath(), bytes);
				}

				return false; //Remove all the patched classes, we don't want these leaking directly on the classpath
			} else {
				return true;
			}
		});

		System.out.println("[OptiLithium] Found " + classCache.getClasses().size() + " patched classes");
		classCache.save(to);
		return classCache;
	}

	private static byte[] md5(File file) throws IOException {
		try (InputStream in = new FileInputStream(file)) {
			return MessageDigest.getInstance("MD5").digest(in.readAllBytes());
		} catch (NoSuchAlgorithmException e) {
			throw new IllegalStateException("MD5 is unavailable", e);
		}
	}

	private static void deleteRecursively(File root) throws IOException {
		Path path = root.toPath();

		if (!Files.exists(path)) return;

		try (Stream<Path> files = Files.walk(path)) {
			files.sorted(Comparator.reverseOrder()).forEach(p -> {
				try {
					Files.deleteIfExists(p);
				} catch (IOException e) {
					throw new UncheckedIOException(e);
				}
			});
		}
	}
}

